Migrated to Flexible Docker Containers

diff --git a/usr/local/bin/nextcloud-cron b/usr/local/bin/nextcloud-cron
--- a/usr/local/bin/nextcloud-cron
+++ b/usr/local/bin/nextcloud-cron
@@ -1,5 +1,4 @@
 #!/bin/bash
-#!/bin/bash
 # Copyright (c) 2022-2023, AllWorldIT.
 #
 # Permission is hereby granted, free of charge, to any person obtaining a copy
@@ -21,6 +20,19 @@
 # IN THE SOFTWARE.
 
 
+# Make sure user is correct
+if [ "$USER" != "www-data" ]; then
+    echo "ERROR: $0 must be run as user www-data"
+    exit 1
+fi
+
 cd /var/www/html
 
-exec su -s /usr/bin/php www-data -- occ "$@"
+# Run cron
+su -s /usr/bin/php www-data cron.php
+
+# Send activity emails
+su -s /usr/bin/php www-data -- occ activity:send-mails
+
+# Send event reminders
+su -s /usr/bin/php www-data -- occ dav:send-event-reminders
